### ISSUE TITLE
should http things be_verifiably_secure?

### ISSUE THREAD

**Issue by jonhiggs** [realestate-com-au/akamai-rspec#18]
should `expect("http://something.com").to be_verifiably_secure` evaluate to true?

**Comment by mmollaverdi** [comment]
I wouldn't say so. Does it?

**Comment by jonhiggs** [comment]
Yep.

**Comment by biancaG** [comment]
That sounds like a bug!

**Comment by grantsheppard** [comment]
@jonhiggs Do you mind sharing the URL that you were testing against?

**Comment by grantsheppard** [comment]
Just tried this against `www.theage.com.au` and confirmed that it is definitely not working as prescribed. My initial thoughts were that it was following a redirect but this certainly isn't the case.

**Comment by grantsheppard** [comment]
Guessing the problems stems from [this](https://github.com/realestate-com-au/akamai-rspec/pull/11#r72387571) change.

This reflects a gap in the tests as well.

**Comment by jonhiggs** [comment]
Thanks Grant. Let me know if you need anything else.

**Comment by biancaG** [comment]
Cool, can we assign someone to fix it or put a card on your wall @mmollaverdi and @grantsheppard?

**Comment by grantsheppard** [comment]
We'll undertake this as part of our custodianship work @biancaG, will discuss with team tomorrow.
